import Head from "next/head";
import { Title } from "@itcase/ui/components/Title";
import { Group } from "@itcase/ui/components/Group";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Group
              direction="vertical"
              padding="20px"
              paddingTablet="15px"
              paddingMobile="10px"
          >
              <Title size="h1" tag="span">
                  Next App
              </Title>
              <Title size="h1" tag="span">
                  Next App
              </Title>
          </Group>
      </main>
    </>
  );
}
